### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by thdotnet** [Jamling/hexo-generator-i18n#1]
Hi,

I've just add your module to my blog, but it's not clear how to setup multiple languages. Do I need to add the options into my _config.yml? Could you please add more information?

Thanks

**Comment by Jamling** [comment]
1. set multi-language at <var>_config.yml</var> under blog root dir

``` yaml
language: [zh,en]
```
1. set language name at <var>source/_data/languages.yml</var>

``` yaml
en: English
zh: 简体中文
```

**Comment by thdotnet** [comment]
Got it. I did the same as you, but I can't open the second language index.html, unless I open the archive folder or the full path with the publication date + name  of the blog:

http://localhost:4000/pt/2016/09/05/hello-world/index.html

Did I miss somethig?

**Comment by Jamling** [comment]
let me see your package.json dependencies and config. the hexo-generator-i18n is the last generator plugin of your hexo blog. 
Refer my blog source: [https://github.com/Jamling/hexo-site](https://github.com/Jamling/hexo-site)

**Comment by thdotnet** [comment]
``` diff
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-admin": "^2.1.0",
    "hexo-all-minifier": "0.0.14",
    "hexo-autonofollow": "^1.0.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
-    "hexo-generator-i18n": "0.0.4",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-index-i18n": "^0.1.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
+    "hexo-generator-i18n": "0.0.4",
    "hexo-server": "^0.2.0"
  }
}

```

**Comment by thdotnet** [comment]
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Thiago Custodio
subtitle: Azure, Software Architecture, Web Development and beyond
description: My technical blog version 2.0
author: Thiago Custodio
language: [en,pt]

timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://thiagocustodio.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: codeland

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

```
