### ISSUE TITLE
只有默认语言的文章会自动生成多语言版本。

### ISSUE THREAD

**Issue by snoozybot** [Jamling/hexo-generator-i18n#5]
Hi， 在用 hexo-generator-i18n 做多语言，发现如果一篇文章只有默认语言的版本，它也会自动在其他语言的文件夹中生成一份，这个功能可以配置取消吗？

**Comment by Jamling** [comment]
请问你的language是怎么配置的？

**Comment by snoozybot** [comment]
```yaml
language: [en, cn]
i18n:
  type: [page, post]
  generator: [index, archive]
```
