### ISSUE TITLE
Can't bring array from language file??

### ISSUE THREAD

**Issue by AhmedBHameed** [Jamling/hexo-generator-i18n#6]
I'm using Hexo with i18n plugin to bring info from language files. But i can't bring array the only result i can extract is the single string.
If this feature is not implemented then it is required otherwise how can i call array of the language file!!??
regards
en.yml

```
team:
    team_info:
        person_1:
              social_media:
                  facebook: '#'
                  twitter: '#'
                  Instagram: '#'
```
`__('team.team_info.person_1.social_media')`
