### ISSUE TITLE
如何实现post的同一篇文章不同语言版本？

### ISSUE THREAD

**Issue by dengcb** [Jamling/hexo-generator-i18n#7]
配置如下：
```
language:
  - en
  - zh
i18n:
  type: [page, post]
  generator: [index, archive, category, tag]
```

我在source目录下建立zh目录，实现了about、category、tag多语言功能。
但是不知道如何才能实现首页index和发帖post的多语言？
我需要一个全站一一对应切换的多语言站点，谢谢！
